// Generated by Wrangler on Wed Aug 14 2024 00:22:28 GMT+0900 (Japan Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	__NEXT_ON_PAGES_KV_SUSPENSE_CACHE: KVNamespace;
	ENDPOINT: string;
}
