// Generated by Wrangler on Wed Aug 14 2024 01:05:16 GMT+0900 (Japan Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	__NEXT_ON_PAGES__KV_SUSPENSE_CACHE: KVNamespace;
	ENDPOINT: string;
}
