name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.0
          cache: "pnpm"
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.0
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"
    
      - name: Install NPM Dependencies
        shell: bash
        run: pnpm install --frozen-lockfile
        working-directory: schedule-next-worker
      - name: create .dev.vars
        run: |
          echo "ENDPOINT=${{ secrets.ENDPOINT }}" > ./.dev.vars
        working-directory: schedule-next-worker
      - name: build
        run: |
          pnpm cloudflare
        working-directory: schedule-next-worker
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: create .dev.vars
        run: |
          echo "ENDPOINT=${{ secrets.ENDPOINT }}" > ./schedule-next-worker/.dev.vars
      - name: Cache turbo build setup
        uses: actions/cache@v4
        with: 
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: migrate
        run: |
          pnpm turbo migrate:remote
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      - name: deploy
        run: |
          pnpm turbo deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          ENDPOINT: ${{ secrets.ENDPOINT }}

        